name: 'Spin plugin releaser'
description: 'Set up your GitHub Actions workflow with a specific version of spin'
author: 'Fermyon Engineering'
inputs:
  template_file:
    required: false
    description: 'the plugin template file'
  github_token:
    required: false
    description: 'github token used for downloading artifacts to render template'
runs:
  using: 'node16'
  main: 'dist/index.js'
